<?php
$lng = Mage::getStoreConfig('storelocator/settings/defaultlon');
$lat = Mage::getStoreConfig('storelocator/settings/defaultlat');
?>
<div id="store-locator-container">
    <h1><?php echo $this->__("Store Locator"); ?></h1>	           
    <div id="form-container">
        <form id="user-location" method="post" action="#">
            <input type="hidden" name="url" value="<?php echo $this->getBaseUrl() . 'storelocator/index/location'; ?>" id="url">
            <input type="hidden" name="searchurl" value="<?php echo $this->getBaseUrl() . 'storelocator/index/searchlocation'; ?>" id="searchurl">
            <input type="hidden" name="url1" value="<?php echo $this->getBaseUrl() . 'storelocator/index/infowindowdescription'; ?>" id="url1">
            <input type="hidden" name="url2" value="<?php echo $this->getBaseUrl() . 'storelocator/index/locationlistdescription'; ?>" id="url2">
            <div id="form-input">
                <label for="address">Enter City OR State OR Phone OR Zip Code:</label>
                <input type="text" id="address" name="address" />
            </div>            
            <button id="submit" type="submit">Submit</button>
        </form>
    </div>

    <div id="map-container">	
        <div id="loc-list">
            <ul id="list"></ul>
        </div>
        <div id="map"></div>
    </div>
</div>

<script type="text/javascript">
    jQuery(function() {
        jQuery('#map-container').storeLocator({'slideMap' : false, 'defaultLoc': true, 'defaultLat': '<?php echo $lat; ?>', 'defaultLng' : '<?php echo $lng; ?>' });
    });
</script>


